[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
cache_path = 'cache'
solc = "0.8.22"
via_ir = true
optimizer = true
optimizer_runs = 200
rpc_url = "https://api.calibration.node.glif.io/rpc/v1"
chain_id = 314159


# For dependencies
remappings = [
    "@ds-test/=lib/ds-test/src/",
    "@solmate/=lib/solmate/src/",
    "@forge-std/=lib/forge-std/src/",
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    "filecoin-solidity-api/=lib/filecoin-solidity-api/",
    "solidity-cborutils/=lib/solidity-cborutils/",
    "@ensdomains/buffer=lib/ensdomains/"
]

# Allow reading test data files
fs_permissions = [{ access = "read", path = "./test" }]

[etherscan]
filecoin-calibration = { key = "", url = "https://filfox.info/api/v1/tools/verifyContract" }
